import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MdToolbarModule,
         MdIconModule,
         MdButtonModule,
         MdCardModule,
         MdListModule,
         MdSlideToggleModule,
         MdGridListModule,
         MdDialogModule,
         MdAutocompleteModule,
         MdMenuModule,
         MdCheckboxModule,
         MdTooltipModule,
         MdDatepickerModule,
         MdRadioModule,
         MdNativeDateModule,
         MdSelectModule,
         MdSidenavModule,
         MdInputModule} from '@angular/material';
import { ConfirmDialogComponent } from './confirm-dialog/confirm-dialog.component';
import {DirectiveModule} from "../directive/directive.module";

@NgModule({
  imports: [
    CommonModule,
    MdToolbarModule,
    MdIconModule,
    MdButtonModule,
    MdCardModule,
    MdInputModule,
    MdSlideToggleModule,
    MdGridListModule,
    MdListModule,
    MdAutocompleteModule,
    MdMenuModule,
    MdDialogModule,
    MdCheckboxModule,
    MdTooltipModule,
    MdDatepickerModule,
    MdRadioModule,
    MdNativeDateModule,
    MdSelectModule,
    MdSidenavModule,
    DirectiveModule,
  ],
  exports: [
    CommonModule,
    MdToolbarModule,
    MdIconModule,
    MdButtonModule,
    MdCardModule,
    MdInputModule,
    MdSlideToggleModule,
    MdListModule,
    MdGridListModule,
    MdAutocompleteModule,
    MdDialogModule,
    MdMenuModule,
    MdCheckboxModule,
    MdTooltipModule,
    MdDatepickerModule,
    MdRadioModule,
    MdNativeDateModule,
    MdSelectModule,
    MdSidenavModule,
    DirectiveModule,
  ],
  entryComponents: [ConfirmDialogComponent],
  declarations: [ConfirmDialogComponent]
})
export class SharedModule { }
